# Generated by Django 5.2.5 on 2025-10-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollabRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(db_index=True, help_text='Unique identifier for the collaboration room', max_length=100, unique=True)),
                ('yjs_state', models.BinaryField(blank=True, help_text='Y.js binary state (state vector)', null=True)),
                ('text_content', models.TextField(blank=True, default='', help_text='Plain text content for simple sync rooms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collaboration Room',
                'verbose_name_plural': 'Collaboration Rooms',
                'ordering': ['-updated_at'],
            },
        ),
    ]
