# Generated by Django 5.2.5 on 2025-11-15 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Exercise name (e.g., 'Bench Press')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Exercise description', null=True)),
                ('muscle_groups', models.CharField(blank=True, help_text='Target muscle groups', max_length=200, null=True)),
                ('equipment_needed', models.CharField(blank=True, help_text='Required equipment', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Workout date and time')),
                ('duration', models.IntegerField(blank=True, help_text='Workout duration in minutes', null=True)),
                ('notes', models.TextField(blank=True, help_text='Session notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField(help_text='Set number (1, 2, 3, etc.)')),
                ('reps', models.IntegerField(blank=True, help_text='Number of repetitions', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in lbs/kg', max_digits=6, null=True)),
                ('rest_time', models.IntegerField(blank=True, help_text='Rest time in seconds', null=True)),
                ('notes', models.CharField(blank=True, help_text='Set-specific notes', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sets', to='workout.exercise')),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sets', to='workout.workoutsession')),
            ],
            options={
                'ordering': ['set_number'],
                'unique_together': {('workout_session', 'exercise', 'set_number')},
            },
        ),
    ]
