# Generated by Django 5.2.5 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_exercise_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='name',
            field=models.CharField(blank=True, help_text='Name for this working set', max_length=200, null=True),
        ),
    ]

